export const navenheter = [
    'Åkrehamn',
    'Ålesund',
    'Alta',
    'Åndalsnes',
    'Arendal',
    'Ås',
    'Åsgårdstrand',
    'Askim',
    'Askøy',
    'Bergen',
    'Bodø',
    'Brevik',
    'Brønnøysund',
    'Brumunddal',
    'Bryne',
    'Drammen',
    'Drøbak',
    'Egersund',
    'Eidsvoll',
    'Elverum',
    'Fagernes',
    'Fauske',
    'Finnsnes',
    'Flekkefjord',
    'Florø',
    'Førde',
    'Fosnavåg',
    'Fredrikstad',
    'Gjøvik',
    'Grimstad',
    'Halden',
    'Hamar',
    'Hammerfest',
    'Harstad',
    'Haugesund',
    'Hokksund',
    'Holmestrand',
    'Hønefoss',
    'Honningsvåg',
    'Horten',
    'Jessheim',
    'Jørpeland',
    'Kirkenes',
    'Kongsberg',
    'Kongsvinger',
    'Kopervik',
    'Kragerø',
    'Kristiansand',
    'Kristiansund',
    'Langesund',
    'Larvik',
    'Leknes',
    'Levanger',
    'Lillehammer',
    'Lillesand',
    'Lillestrøm',
    'Lyngdal',
    'Mandal',
    'Moelv',
    'Mo i Rana',
    'Molde',
    'Mosjøen',
    'Moss',
    'Nærøy',
    'Namsos',
    'Narvik',
    'Nesoddtangen',
    'Notodden',
    'Odda',
    'Orkanger',
    'Oslo',
    'Otta',
    'Porsgrunn',
    'Raufoss',
    'Risør',
    'Rjukan',
    'Sandefjord',
    'Sandnes',
    'Sandnessjøen',
    'Sandvika',
    'Sauda',
    'Ski',
    'Skien',
    'Sortland',
    'Stavanger',
    'Stavern',
    'Steinkjer',
    'Stjørdal',
    'Stokmarknes',
    'Stord',
    'Svelvik',
    'Svolvær',
    'Tønsberg',
    'Tromsø',
    'Trondheim',
    'Tvedestrand',
    'Ulsteinvik',
    'Vadsø',
    'Vardø',
    'Farsund',
    'Måløy',
    'Verdal',
    'Vestby',
    'Vinstra',
]

export const land = [
    'Afghanistan',
    'Albania',
    'Algerie',
    'Amerikansk Samoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antarktis',
    'Antigua og Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgia',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Bosnia-Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei Darussalam',
    'Bulgaria',
    'Burkina Faso',
    'Burma',
    'Burundi',
    'Cambodia',
    'Canada',
    'Cape Verde',
    'Cayman Islands',
    'Central African Republic',
    'Chad',
    'Chile',
    'Christmasøya',
    'Clipperton Island',
    'Colombia',
    'Comoros',
    'Cook øyene',
    'Costa Rica',
    'Cote d’Ivoire',
    'Croatia',
    'Cuba',
    'Danmark',
    'Djibouti',
    'Dominica',
    'Dominikanske Republikk',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'Fiji',
    'Filipinene',
    'Finland',
    'Forente Arabiske Emirater',
    'Frankrike',
    'Fransk Guiana',
    'Fransk Polynesia',
    'Færøyene',
    'Gabon',
    'Gambia',
    'Georgia',
    'Ghana',
    'Gibraltar',
    'Grenada',
    'Grønnland',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Hellas',
    'Honduras',
    'Hong Kong',
    'India',
    'Indonesia',
    'Irak',
    'Iran',
    'Irland',
    'Island',
    'Israel',
    'Italia',
    'Jamaica',
    'Jan Mayen',
    'Japan',
    'Jersey',
    'Jomfruøyene',
    'Jordan',
    'Jugoslavia',
    'Kamerun',
    'Kazakhstan',
    'Kenya',
    'Kina',
    'Kiribati',
    'Kongo',
    'Kongo',
    'Kuwait',
    'Kypros',
    'Kirgististan',
    'Laos',
    'Latvia',
    'Lesotho',
    'Libanon',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macao',
    'Madagascar',
    'Makedonia',
    'Malawi',
    'Malaysia',
    'Maldivene',
    'Mali',
    'Malta',
    'Man',
    'Marshallsøyene',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Mexico',
    'Micronesia Føderale Stater',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montserrat',
    'Morocco',
    'Mozambique',
    'Namibia',
    'Nauru',
    'Nederland',
    'Nederlandske Antiller',
    'Nepal',
    'New Caledonia',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Nord-Korea',
    'Norfolk Island',
    'Norge',
    'Northern Mariana Islands',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestina',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Polen',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Réunion',
    'Romania',
    'Russland',
    'Rwanda',
    'Saint Helena',
    'Saint Kitts og Nevis',
    'Saint Lucia',
    'Saint Vincent og the Grenadines',
    'Samoa',
    'San Marino',
    'São Tomé og Príncipe',
    'Saudi Arabia',
    'Senegal',
    'Seychellene',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomonsøyene',
    'Somalia',
    'Spania',
    'Sri Lanka',
    'Storbritannia',
    'Sudan',
    'Suriname',
    'Svalbard',
    'Sveits',
    'Sverige',
    'Swaziland',
    'Syria',
    'Sør-Afrika',
    'Sør-Korea',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tonga',
    'Trinidad og Tobago',
    'Tsjekkia',
    'Tunisia',
    'Turkmenistan',
    'Turks- og Caicosøyene',
    'Tyrkia',
    'Tyskland',
    'Uganda',
    'Ukraina',
    'Ungarn',
    'Uruguay',
    'USA',
    'Uzbekistan',
    'Vanuatu',
    'Vatikanet',
    'Venezuela',
    'Vietnam',
    'Wallis og Futuna',
    'Yemen',
    'Zambia',
    'Zimbabwe',
    'Østerrike',
]
